server {
    listen 80;
    server_name localhost;

    # CSP – autoriser les appels Google Places, images externes, etc.
    add_header Content-Security-Policy
        "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' ka-f.fontawesome.com; font-src 'self' ka-f.fontawesome.com; img-src 'self' data: blob: api.qrserver.com upload.wikimedia.org drive.google.com raw.githubusercontent.com; connect-src 'self' *.googleapis.com ka-f.fontawesome.com unpkg.com; worker-src 'self' blob:;"
        always;

    # 1. Servir les fichiers Statiques (Au lieu du proxy)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. L'API reste en Proxy vers le backend
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
