version: "3.8"

services:
  # Base de données
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mobility_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  # Backend Node.js
  backend:
    # Changement ici : :main au lieu de :latest
    image: registry.eirb.fr/mobiliteirb/backend:main
    environment:
      DATABASE_URL: postgres://user:${DB_PASSWORD}@db:5432/mobility_db
      PORT: 3000
      FRONTEND_URL: https://mobilit.eirb.fr
      EIRB_CONNECT_CLIENT_ID: ${EIRB_CLIENT_ID}
      EIRB_CONNECT_CLIENT_SECRET: ${EIRB_CLIENT_SECRET}
    networks:
      - app-network
    depends_on:
      - db
    restart: always

  # Frontend (Nuxt SSR avec reverse proxy Nginx)
  frontend:
    # Changement ici : :main au lieu de :latest
    image: registry.eirb.fr/mobiliteirb/frontend:main
    environment:
      NUXT_PUBLIC_API_BASE: /api
      NODE_ENV: production
    networks:
      - app-network
    restart: always

  # Reverse proxy Nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "10077:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    restart: always

networks:
  app-network:

volumes:
  pgdata:
