version: "3.8"

services:
  # Base de données
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mobility_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  # Backend Node.js
  backend:
    # Regarde les logs de ton GitHub Action 'build-and-push' pour avoir le nom exact.
    image: registry.eirb.fr/mobiliteirb/mobiliteirb-backend:latest
    environment:
      # ICI : On injecte le mot de passe dynamique dans l'URL de connexion
      DATABASE_URL: postgres://user:${DB_PASSWORD}@db:5432/mobility_db
      PORT: 3000
      # URLs pour l'Auth EirbConnect
      FRONTEND_URL: https://mobilit.eirb.fr
      EIRB_CONNECT_CLIENT_ID: ${EIRB_CLIENT_ID}
      EIRB_CONNECT_CLIENT_SECRET: ${EIRB_CLIENT_SECRET}
    networks:
      - app-network
    depends_on:
      - db
    restart: always

  # Frontend (Nginx)
  frontend:
    # VERIFIE LE NOM ICI AUSSI
    image: registry.eirb.fr/mobiliteirb/mobiliteirb-frontend:latest
    ports:
      - "1077:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

networks:
  app-network:

volumes:
  pgdata:
