name: Build and Deploy Mobility App

on:
    push:
        branches: ["main"]

jobs:
    # 1. Construction du Backend
    build-and-push-back:
        permissions:
            contents: read
            id-token: write
        uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
        with:
            file: "./backend/Dockerfile"
            image_name: "mobiliteirb/backend"
            context: "./backend"
        # ON FORCE LE MAPPING ICI (Gauche = attendu par Eirbware, Droite = tes secrets)
        secrets:
            registry_username: ${{ secrets.REGISTRY_USERNAME }}
            registry_api_key: ${{ secrets.REGISTRY_API_KEY }}

    # 2. Préparation des variables d'environnement pour le Front
    create-env:
        runs-on: ubuntu-latest
        steps:
            - name: Create .env file for Frontend
              run: |
                  echo "VITE_API_URL=https://mobilit.eirb.fr/api" > .env
            - name: Upload .env file
              uses: actions/upload-artifact@v4
              with:
                  name: env_file
                  path: .env
                  include-hidden-files: true

    # 3. Construction du Frontend
    build-and-push-front:
        needs: create-env
        permissions:
            contents: read
            id-token: write
        uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
        with:
            file: "./frontend/Dockerfile"
            image_name: "mobiliteirb/frontend"
            context: "./frontend"
            artifact_name: env_file
        # IDEM ICI
        secrets:
            registry_username: ${{ secrets.REGISTRY_USERNAME }}
            registry_api_key: ${{ secrets.REGISTRY_API_KEY }}

    # 4. Déploiement sur Portainer
    deploy:
        needs: [build-and-push-back, build-and-push-front]
        uses: Eirbware/.github/.github/workflows/deploy-stack.yml@master
        # Pour le deploy, on peut laisser inherit ou mapper aussi si ça plante
        secrets:
            portainer_stack_webhook: ${{ secrets.PORTAINER_STACK_WEBHOOK }}
            wireguard_conf: ${{ secrets.WIREGUARD_CONF }}
